# fly.toml app configuration file generated for message-system on 2025-03-29T17:48:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'message-system'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3012
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[http]
  max_request_body_size = "10MB"  # 调整HTTP请求体大小限制
