import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { before, after, describe, it } from 'node:test';
import { createPostgresPool } from './postgresPool';
import { PostgresStore, PostgresPool } from './postgresStore';
import {PersonalAgentScheduler} from '../services/personalAgentScheduler';
import {PersonalAgentTaskService} from '../services/personalAgentTasks';
import { PersonalAgentFile } from '../types';
const url=process.env.ROOM_EVENT_TEST_DATABASE_URL;
if(url&&!/(^|[_-])(test|e2e)([_-]|$)/i.test(new URL(url).pathname.slice(1)))throw Error('Personal files require a test database');
const logger={ info(){},warn(){},error(){},debug(){} },owner=`files-${randomUUID()}`,other=`files-other-${randomUUID()}`;
describe('personal files PostgreSQL',{ skip: !url },()=>{
  let pool: PostgresPool,store: PostgresStore;
  before(async()=>{
    pool=createPostgresPool(url!,logger as any);store=new PostgresStore(pool,logger as any);await store.initializeSchema();
    for(const clientId of [owner,other]){await store.createPasswordAccountForClient({ clientId,accountId:clientId,now:new Date().toISOString() });await store.ensurePersonalAgentProfile(clientId);}
  });
  after(async()=>{if(pool){await pool.query('DELETE FROM rooms WHERE creator_id=ANY($1::text[])',[[owner,other]]);await pool.query('DELETE FROM accounts WHERE id=ANY($1::text[])',[[owner,other]]);await pool.end?.();}});
  const record=(): PersonalAgentFile=>{const id=randomUUID();return { id,clientId:owner,name:'real.pdf',byteSize:200,pageCount:1,fields:[{ name:'Name',type:'text',value:'' }],objectKey:`personal-files/${id}`,source:'Imported by you',createdAt:new Date().toISOString() };};
  it('persists owner documents, keeps copies distinct and rejects cross-owner parents',async()=>{
    const original=(await store.savePersonalAgentFile(record()))!;assert.ok(original);
    const copy=(await store.savePersonalAgentFile({ ...record(),parentId:original.id }))!;assert.ok(copy);assert.equal(copy.parentId,original.id);
    assert.equal((await store.readPersonalAgentFiles(other,{ id:original.id })).total,0);
    assert.equal(await store.savePersonalAgentFile({ ...record(),clientId:other,parentId:original.id }),null);
    assert.equal((await store.readPersonalAgentFiles(owner)).total,2);
  });
  it('accepts only a live owner turn when a source claim is supplied',async()=>{
    const room=await store.createPersonalAgentThread(owner,'File source'),turnId=randomUUID(),now=new Date().toISOString();
    await store.upsertRoomAgentTurn({ id:turnId,roomId:room.id,backend:'codex-app-server',assistantName:'Personal Agent',status:'running',startedAt:now,updatedAt:now });
    const lease=(await store.acquireCodeAgentRoomLease(room.id,turnId,'file-test',now,60000))!;assert.ok(lease);
    assert.ok(await store.savePersonalAgentFile(record(),{ roomId:room.id,turnId }));
    await store.releaseCodeAgentRoomLease(room.id,turnId,'file-test',lease.fence);
    assert.equal(await store.savePersonalAgentFile(record(),{ roomId:room.id,turnId }),null);
  });
  it('hydrates actual task files and independent browser sessions after restart',async()=>{
    const source=await store.createPersonalAgentThread(owner,'Task with real artifacts'),browser=await store.createPersonalAgentThread(owner,'Independent browser'),turnId=randomUUID(),now=new Date().toISOString();
    await store.upsertRoomAgentTurn({id:turnId,roomId:source.id,backend:'codex-app-server',assistantName:'Agent',status:'running',startedAt:now,updatedAt:now});
    const sourceLease=(await store.acquireCodeAgentRoomLease(source.id,turnId,'task-artifact-test',now,60000))!;
    const browserLease=(await store.acquireCodeAgentRoomLease(browser.id,'browser-control:artifacts','task-artifact-test',now,60000))!;
    const original=(await store.savePersonalAgentFile(record(),{roomId:source.id,turnId}))!;
    const copy=(await store.savePersonalAgentFile({...record(),parentId:original.id},{roomId:source.id,turnId}))!;
    const session={id:randomUUID(),roomId:browser.id,clientId:owner,url:'https://example.com/actual',title:'Saved actual browser',encryptedState:'private-login-state',previewObjectKey:'private-preview',status:'active' as const,updatedAt:now};
    assert.equal(await store.savePersonalAgentBrowser(session,browserLease.turnId,{id:randomUUID(),clientId:owner,roomId:source.id,turnId,url:session.url,title:session.title,objectKey:`actual-browser/${randomUUID()}`,createdAt:now}),true);
    const restarted=new PersonalAgentTaskService(new PostgresStore(pool,logger as any) as any),detail=await restarted.detail(owner,source.id);
    assert.deepEqual(new Set(detail.files.map(file=>file.id)),new Set([original.id,copy.id]));
    assert.equal(detail.browsers[0].id,session.id);assert.equal(detail.browsers[0].roomId,browser.id);assert.ok(detail.browsers[0].previewUrl);
    assert.equal('encryptedState' in detail.browsers[0],false);assert.equal('previewObjectKey' in detail.browsers[0],false);assert.equal('objectKey' in detail.files[0],false);
    const visit=(await store.readPersonalAgentBrowserObservations(owner,{roomId:source.id})).observations[0];
    assert.equal(visit.sessionId,session.id);assert.equal(visit.browserRoomId,browser.id);assert.equal(visit.turnId,turnId);
    assert.equal((await store.readPersonalAgentFiles(owner,{roomId:browser.id})).total,0);
    assert.equal((await store.readPersonalAgentFiles(other,{roomId:source.id})).total,0);
    await assert.rejects(restarted.detail(other,source.id),/not found/);
    const next=await store.createPersonalAgentThread(owner,'Cached attachment in another task'),nextId=randomUUID();
    await store.upsertRoomAgentTurn({id:nextId,roomId:next.id,backend:'codex-app-server',assistantName:'Agent',status:'running',startedAt:now,updatedAt:now});
    const nextLease=(await store.acquireCodeAgentRoomLease(next.id,nextId,'task-artifact-test',now,60000))!;
    assert.equal(await store.linkPersonalAgentTaskFile(owner,original.id,{roomId:next.id,turnId:nextId}),true);
    assert.equal((await store.readPersonalAgentFiles(owner,{roomId:next.id})).files[0].id,original.id);
    assert.equal((await store.readPersonalAgentFiles(owner,{roomId:source.id})).total,2);
    assert.equal(await store.linkPersonalAgentTaskFile(other,original.id,{roomId:next.id,turnId:nextId}),false);
    await pool.query("UPDATE rooms SET personal_agent_task_control='paused' WHERE id=$1",[next.id]);
    assert.equal(await store.savePersonalAgentFile(record(),{roomId:next.id,turnId:nextId}),null);
    assert.equal(await store.linkPersonalAgentTaskFile(owner,copy.id,{roomId:next.id,turnId:nextId}),false);
    await store.releaseCodeAgentRoomLease(next.id,nextId,'task-artifact-test',nextLease.fence);
    await store.releaseCodeAgentRoomLease(source.id,turnId,'task-artifact-test',sourceLease.fence);
    await store.releaseCodeAgentRoomLease(browser.id,browserLease.turnId,'task-artifact-test',browserLease.fence);
  });
  it('persists requested PDF inputs and user answers across service instances',async()=>{
    const room=await store.createPersonalAgentThread(owner,'Input workflow'),turnId=randomUUID(),now=new Date().toISOString();
    await store.upsertRoomAgentTurn({id:turnId,roomId:room.id,backend:'codex-app-server',assistantName:'Agent',status:'running',startedAt:now,updatedAt:now});
    const lease=(await store.acquireCodeAgentRoomLease(room.id,turnId,'input-test',now,60000))!;
    const file=(await store.savePersonalAgentFile(record()))!;
    const scheduler=new PersonalAgentScheduler(store as any,{resumeQueuedTurns:async()=>{}},logger as any,{selectedModel:{id:'gpt-5',apiModel:'gpt-5',provider:'openai',label:'GPT',description:''}});
    const continuation={create:(clientId:string,roomId:string,content:string)=>scheduler.createQueuedMessage(clientId,roomId,content),wake:async()=>{}};
    const service=new PersonalAgentTaskService(store as any,continuation);
    const saved=await service.request({clientId:owner,roomId:room.id,turnId},{question:'What is your name?',fileId:file.id,fields:['Name']});
    const restarted=new PersonalAgentTaskService(store as any,continuation);
    assert.equal((await restarted.detail(owner,room.id)).requests[0].id,saved.request.id);
    await restarted.answer(owner,room.id,saved.request.id,{fields:{Name:'Confirmed owner'}});
    assert.equal((await service.detail(owner,room.id)).requests[0].answer!.fields.Name,'Confirmed owner');
    const queued=(await store.readMessagePageByRoom(room.id,{limit:100})).messages.filter(message=>message.codeAgentQueuedInput?.state==='queued');
    assert.equal(queued.length,1);assert.match(queued[0].content,/Confirmed owner/);
    await restarted.answer(owner,room.id,saved.request.id,{fields:{Name:'Repeated'}});
    assert.equal((await store.readMessagePageByRoom(room.id,{limit:100})).messages.length,1);
    assert.equal((await store.readPersonalAgentInputRequests(other,room.id)).length,0);
    await assert.rejects(service.answer(other,room.id,saved.request.id,{fields:{Name:'Other'}}),/not found/);
    const second=await service.request({clientId:owner,roomId:room.id,turnId},{question:'Confirm another value',fileId:file.id,fields:['Name']});
    await Promise.all(['First','Second'].map(Name=>service.answer(owner,room.id,second.request.id,{fields:{Name}})));
    const answers=(await store.readMessagePageByRoom(room.id,{limit:100})).messages;
    assert.equal(answers.length,2);
    const confirmed=(await service.detail(owner,room.id)).requests.find(request=>request.id===second.request.id)!;
    assert.equal(answers.filter(message=>message.content.includes(`"Name":"${confirmed.answer!.fields.Name}"`)).length,1);
    const cancelled=await service.request({clientId:owner,roomId:room.id,turnId},{question:'Do not restart this cancelled task'});
    await store.upsertRoomAgentTurn({id:turnId,roomId:room.id,status:'cancelled',startedAt:new Date().toISOString(),backend:'codex-app-server',assistantName:'Agent',updatedAt:new Date().toISOString()});
    await assert.rejects(service.answer(owner,room.id,cancelled.request.id,{text:'Resume anyway'}),/Cancelled tasks cannot continue/);
    assert.equal((await store.readMessagePageByRoom(room.id,{limit:100})).messages.length,2);
    await store.releaseCodeAgentRoomLease(room.id,turnId,'input-test',lease.fence);
    await assert.rejects(service.request({clientId:owner,roomId:room.id,turnId},{question:'Ended'}),/ended/);
  });

});
