import { A2UI_BASIC_CATALOG_ID } from './a2uiPayload';

export const buildE2EFakeA2UIBatches = (surfaceId: string, prompt: string): unknown[][] => [
  [{
    version: 'v0.9',
    createSurface: { surfaceId, catalogId: A2UI_BASIC_CATALOG_ID },
  }],
  [{
    version: 'v0.9',
    updateComponents: {
      surfaceId,
      components: [
        { id: 'root', component: 'Card', child: 'body' },
        { id: 'body', component: 'Column', children: ['header', 'summary', 'divider', 'status_row', 'checklist_title', 'checklist', 'controls_title', 'controls', 'actions'], align: 'stretch' },
        { id: 'header', component: 'Row', children: ['title_group', 'phase'], align: 'center', justify: 'spaceBetween' },
        { id: 'title_group', component: 'Row', children: ['surface_icon', 'title'], align: 'center' },
        { id: 'surface_icon', component: 'Icon', name: 'info' },
        { id: 'title', component: 'Text', text: { path: '/title' }, variant: 'h3' },
        { id: 'phase', component: 'Text', text: { path: '/phase' }, variant: 'caption' },
        { id: 'summary', component: 'Text', text: { path: '/body' }, variant: 'body' },
        { id: 'divider', component: 'Divider' },
        { id: 'status_row', component: 'Row', children: ['status_label', 'status_value'], align: 'center' },
        { id: 'status_label', component: 'Text', text: 'Status', variant: 'caption' },
        { id: 'status_value', component: 'Text', text: { path: '/status' }, variant: 'body' },
        { id: 'checklist_title', component: 'Text', text: 'Streaming checkpoints', variant: 'h5' },
        { id: 'checklist', component: 'List', children: ['item_1', 'item_2', 'item_3'], direction: 'vertical' },
        { id: 'item_1', component: 'Text', text: { path: '/item1Text' } },
        { id: 'item_2', component: 'Text', text: { path: '/item2Text' } },
        { id: 'item_3', component: 'Text', text: { path: '/item3Text' } },
        { id: 'controls_title', component: 'Text', text: 'Native catalog controls', variant: 'h5' },
        {
          id: 'controls',
          component: 'Tabs',
          tabs: [
            { title: 'Inputs', child: 'input_column' },
            { title: 'Media', child: 'media_column' },
          ],
        },
        { id: 'input_column', component: 'Column', children: ['name_field', 'ready_check', 'choice_picker', 'confidence_slider', 'date_input', 'details_modal'], align: 'stretch' },
        { id: 'name_field', component: 'TextField', label: 'Reviewer', value: { path: '/reviewer' }, variant: 'shortText' },
        { id: 'ready_check', component: 'CheckBox', label: 'Ready to submit feedback', value: { path: '/ready' } },
        {
          id: 'choice_picker',
          component: 'ChoicePicker',
          label: 'Preferred next step',
          variant: 'mutuallyExclusive',
          options: [
            { label: 'Keep streaming', value: 'stream' },
            { label: 'Open details', value: 'details' },
            { label: 'Export summary', value: 'export' },
          ],
          value: { path: '/selectedNextStep' },
          displayStyle: 'chips',
        },
        { id: 'confidence_slider', component: 'Slider', label: 'Confidence', min: 0, max: 100, value: { path: '/confidence' } },
        { id: 'date_input', component: 'DateTimeInput', label: 'Review time', value: { path: '/reviewAt' }, enableDate: true, enableTime: true },
        { id: 'details_modal', component: 'Modal', trigger: 'details_trigger', content: 'details_content' },
        {
          id: 'details_trigger',
          component: 'Button',
          child: 'details_trigger_text',
          action: { event: { name: 'a2ui_demo_open_details', context: { source: 'e2e_fake_ai' } } },
        },
        { id: 'details_trigger_text', component: 'Text', text: 'Open details' },
        { id: 'details_content', component: 'Card', child: 'details_text' },
        { id: 'details_text', component: 'Text', text: { path: '/modalText' } },
        { id: 'media_column', component: 'Column', children: ['sample_image', 'sample_audio', 'sample_video', 'media_caption'], align: 'stretch' },
        { id: 'sample_image', component: 'Image', url: { path: '/imageUrl' }, description: 'A2UI placeholder image', fit: 'cover', variant: 'smallFeature' },
        { id: 'sample_audio', component: 'AudioPlayer', url: { path: '/audioUrl' }, description: 'Sample audio' },
        { id: 'sample_video', component: 'Video', url: { path: '/videoUrl' } },
        { id: 'media_caption', component: 'Text', text: { path: '/mediaCaption' }, variant: 'caption' },
        { id: 'actions', component: 'Row', children: ['acknowledge'], align: 'center', justify: 'end' },
        {
          id: 'acknowledge',
          component: 'Button',
          child: 'acknowledge_text',
          variant: 'primary',
          action: { event: { name: 'a2ui_demo_acknowledge', context: { prompt: { path: '/prompt' }, source: 'e2e_fake_ai' } } },
        },
        { id: 'acknowledge_text', component: 'Text', text: { path: '/ctaLabel' } },
      ],
    },
  }],
  ...[
    {
      phase: '2/4 chunks',
      body: 'This surface is already visible while the assistant text stream continues.',
      status: 'Creating the component tree and binding live data.',
      item1Text: 'createSurface emitted before the first text chunk settled.',
      item2Text: 'The native component catalog is rendering.',
      item3Text: 'Later data updates will reuse this component tree.',
      selectedNextStep: ['stream'],
      confidence: 60,
    },
    {
      phase: '3/4 chunks',
      body: 'The UI model is updating independently of the markdown stream.',
      status: 'A later data model update arrived before the final text chunk.',
      item1Text: 'The surface ID remained stable.',
      item2Text: 'The component tree was reused.',
      item3Text: 'New values are streaming into the same surface.',
      selectedNextStep: ['details'],
      confidence: 78,
    },
    {
      phase: 'Complete',
      body: 'The surface finished before ai_stream_end and is stored with the final message.',
      status: 'Ready for client actions.',
      item1Text: 'The server emitted validated A2UI v0.9 updates.',
      item2Text: 'The client rendered them incrementally.',
      item3Text: 'The cumulative payload is now durable.',
      selectedNextStep: ['export'],
      confidence: 92,
    },
  ].map((state, index) => [{
    version: 'v0.9',
    updateDataModel: {
      surfaceId,
      path: '/',
      value: {
        title: 'Streaming A2UI',
        prompt,
        ctaLabel: 'Send UI action',
        reviewer: 'RoomTalk',
        ready: true,
        reviewAt: `2026-06-13T12:${String(index * 5).padStart(2, '0')}:00-07:00`,
        modalText: 'The modal, controls, and media preview share the streamed data model.',
        imageUrl: 'https://placehold.co/640x360/png?text=Streaming+A2UI',
        audioUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3',
        videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
        mediaCaption: 'Media components update without replacing the component tree.',
        ...state,
      },
    },
  }]),
];
